In [1]:
import torch
import numpy as np


### Tensor 초기화

In [10]:
# 1. 원 데이터로부터 바로 생성
data = [[1,2],[3,4]]
tensor_data = torch.tensor(data)

# 2. numpy 배열로부터 생성
np_array =np.array(data)
x_np=torch.from_numpy(np_array)

# 3. 다른 텐서로부터 생성하기
# 명시적으로 override하지 않으면, 기존의 텐서 속성을 유지한다.
x_ones = torch.ones_like(tensor_data)
print(f"ones tensor: \n {x_ones}\n")

x_rand = torch.rand_like(tensor_data, dtype=torch.float)
print(f"random tensor: \n {x_rand}\n")

# 4. 형태 지정하여 텐서 만들기
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"random tensor using shape: \n{rand_tensor}\n")
print(f"ones tensor using shape: \n{ones_tensor}\n")
print(f"zeros tensor using shape: \n{zeros_tensor}\n")

ones tensor: 
 tensor([[1, 1],
        [1, 1]])

random tensor: 
 tensor([[0.2664, 0.0542],
        [0.5950, 0.8755]])

random tensor using shape: 
tensor([[0.4984, 0.2510, 0.9188],
        [0.1656, 0.7197, 0.6465]])

ones tensor using shape: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])

zeros tensor using shape: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])



### 텐서의 속성
텐서의 속성은 shape, datatype, 저장위치가 있다.

In [11]:
tensor = torch.rand(3,4)
print(f"tensor shape: {tensor.shape}")
print(f"tensor datatype: {tensor.dtype}")
print(f"device tensor stored: {tensor.device}")

tensor shape: torch.Size([3, 4])
tensor datatype: torch.float32
device tensor stored: cpu


### 텐서 연산
기본 numpy 연산과 거의 비슷?
각 연산들은 모두 GPU에서 사용가능하다. -> 병렬연산이 빠른 GPU에서 학습이 빠른 이유

In [13]:
# GPU가 존재하면 텐서를 gpu로 이동한다.
if torch.cuda.is_available():
    tensor=tensor.to("cuda")
print(torch.cuda.is_available())

False


In [21]:
# 산수 연산
# 두 텐서 간의 행렬 곱을 계산한다. y1,y2,y3은 모두 같은 결과를 낸다.

y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(y1)
torch.matmul(tensor,tensor.T,out=y3)


# element wise을 계산한다.
z1 = tensor*tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor,tensor,out=z3)

# 단일 요소 텐서의 모든 값을 하나로 집계하여 요소가 하나인 텐서의 경우, item()을 사용하여 python숫자로 변환 가능
agg = tensor.sum()
agg_item = agg.item()
print(type(agg_item))

<class 'float'>
